// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"koutube-tg-reply/internal/http"
	"koutube-tg-reply/internal/koutube-conv"
	"koutube-tg-reply/internal/og"
	"koutube-tg-reply/internal/page"
	"koutube-tg-reply/internal/tg"
	"koutube-tg-reply/internal/ytdl"
)

// Injectors from wire.go:

func New() (*App, error) {
	config := NewConfig()
	token := config.Token
	baseURL := config.BaseURL
	converter := koutube_conv.NewConverter(baseURL)
	logger, err := newLogger()
	if err != nil {
		return nil, err
	}
	bot := tg.New(token, converter, logger)
	httpPort := config.HTTPort
	builder := og.NewBuilder()
	youtubeDL := ytdl.NewYoutubeDL()
	service := page.NewService(builder, youtubeDL)
	server := http.NewServer(httpPort, service)
	app, err := newApp(bot, server)
	if err != nil {
		return nil, err
	}
	return app, nil
}
