// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"koutube-tg-reply/internal/koutube-conv"
	"koutube-tg-reply/internal/proxy"
	"koutube-tg-reply/internal/tg"
)

// Injectors from wire.go:

func New() (*App, error) {
	config := NewConfig()
	token := config.Token
	converter := koutube_conv.NewConverter()
	logger, err := newLogger()
	if err != nil {
		return nil, err
	}
	bot := tg.New(token, converter, logger)
	proxyPort := config.HTTPort
	server := proxy.NewServer(proxyPort, converter)
	app, err := newApp(bot, server)
	if err != nil {
		return nil, err
	}
	return app, nil
}
